### ISSUE TITLE
Contrail-controller http-services relation pushes SSL

### ISSUE THREAD

**Issue by majduk** [Juniper/contrail-charms#147]
Contrail controller http-services relation to haproxy pushes SSL monitoring configuration. Below is the relation data:
```  - servers:
    - [contrail-controller-0, 172.27.105.64, 8082, check inter 2000 rise 2 fall 3 ssl
        verify none]
    service_host: 172.27.104.43
    service_name: contrail-api
    service_options: [timeout client 3m, option nolinger, timeout server 3m, balance
        source]
    service_port: 8082
egress-subnets: 172.27.105.69/32
ingress-address: 172.27.105.69
private-address: 172.27.105.69
```
Note that in case contrail-api is exposed without SSL, that renders haproxy configuration with an SSL check which in turns prevents contrail-api from operating as haproxy considers all backend API servers as down.

**Comment by Andrey-mp** [comment]
Hi @majduk , did you read readme on main page of the project?

**Comment by majduk** [comment]
Yes, I did. Can you point me to a place you are referring to?

**Comment by Andrey-mp** [comment]
https://github.com/Juniper/contrail-charms
Master branch was copied to R4 branch. Please use R4 branch to deploy 4.x releases and R5 branch to deploy 5.x releases.

https://github.com/Juniper/contrail-charms/tree/R5
Content was moved to github.com/tungstenfabric/tf-charms to branch master

then please check commits in https://github.com/tungstenfabric/tf-charms - 
https://github.com/tungstenfabric/tf-charms/commit/156225b559a3b8de4e0ce7c3ee829447dfc056c8

this issue was fixed yesterday.
